server:
  port: 7002

#Eureka配置
eureka:
  instance:
    # eureka服务端实力名称
    hostname: 127.0.0.1
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://127.0.0.1:7002/eureka/
      # 集群，相互注册，相互守望，7001注册到7002，7002注册到7001
      # defaultZone: http://localhost:7001/eureka/

